FROM openjdk:8-jdk-alpine
MAINTAINER javier.rg@protonmail.com
EXPOSE 8080 
ADD target/ricoh-demo-articulo-server.jar ricoh-demo-articulo-server.jar
ENTRYPOINT ["java","-jar","ricoh-demo-articulo-server.jar"]