FROM openjdk:8-jdk-alpine
MAINTAINER javier.rg@protonmail.com
EXPOSE 8081 
ADD target/ricoh-demo-pedido-server.jar ricoh-demo-pedido-server.jar
ENTRYPOINT ["java","-jar","ricoh-demo-pedido-server.jar"]