-- Drop table
/* DROP TABLE IF EXISTS PEDIDO_ARTICULO;
DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS ARTICULO;
DROP TABLE IF EXISTS CATALOGO; */
DROP ALL OBJECTS;

CREATE TABLE CATALOGO (
	ID INTEGER NOT NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
	CONSTRAINT PK_CATALOGO PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_3 ON CATALOGO (ID);

-- Drop table
-- DROP TABLE ARTICULO
CREATE TABLE ARTICULO (
	ID INTEGER NOT NULL,
	ID_CATALOGO INTEGER DEFAULT 0 NOT NULL,
	PRECIO INTEGER DEFAULT 0 NOT NULL,
	DESCRIPCION VARCHAR(50) DEFAULT '0' NOT NULL,
	CONSTRAINT PK_ARTICULO PRIMARY KEY (ID),
	CONSTRAINT FK_ARTICULO_CATALOGO FOREIGN KEY (ID_CATALOGO) REFERENCES CATALOGO(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX FK_ARTICULO_CATALOGO ON ARTICULO (ID_CATALOGO);
CREATE UNIQUE INDEX PRIMARY_KEY_E ON ARTICULO (ID);

-- Drop table
-- DROP TABLE PEDIDO
CREATE TABLE PEDIDO (
	ID INTEGER NOT NULL,
	CLIENTE VARCHAR(50) NOT NULL,
	CONSTRAINT PK_PEDIDO PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_8 ON PEDIDO (ID);

-- Drop table
-- DROP TABLE PEDIDO_ARTICULO
CREATE TABLE PEDIDO_ARTICULO (
	ID INTEGER NOT NULL,
	ID_PEDIDO INTEGER DEFAULT 0 NOT NULL,
	ID_ARTICULO INTEGER DEFAULT 0 NOT NULL,
	CONSTRAINT PK_PEDIDO_ARTICULO PRIMARY KEY (ID),
	CONSTRAINT FK_PEDIDO_ARTICULO_ARTICULO FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FK_PEDIDO_ARTICULO_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX FK_PEDIDO_ARTICULO_ARTICULO ON PEDIDO_ARTICULO (ID_ARTICULO);
CREATE INDEX FK_PEDIDO_ARTICULO_PEDIDO ON PEDIDO_ARTICULO (ID_PEDIDO);
CREATE UNIQUE INDEX PRIMARY_KEY_5 ON PEDIDO_ARTICULO (ID);